const constants = {
  ADD_DRIVER_OR_ASSISTANT: "ADD_DRIVER_OR_ASSISTANT",
  ADD_DRIVER_OR_ASSISTANT_SUCCESS: "ADD_DRIVER_OR_ASSISTANT_SUCCESS",
  ADD_DRIVER_OR_ASSISTANT_ERROR: "ADD_DRIVER_OR_ASSISTANT_ERROR",
  ADD_DRIVER_OR_ASSISTANT_FORM_DATA: "ADD_DRIVER_OR_ASSISTANT_FORM_DATA",
  ADD_SUPPLIER: "ADD_SUPPLIER",
  ADD_SUPPLIER_SUCCESS: "ADD_SUPPLIER_SUCCESS",
  ADD_SUPPLIER_ERROR: "ADD_SUPPLIER_ERROR",
  ADD_SUPPLIER_FORM_DATA: "ADD_SUPPLIER_FORM_DATA",
  DRIVER: "driver",
  ASSISTANT: "assistant"
};

export default constants;
