const constants = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_FORMDATA: "LOGIN_FORMDATA",

  SIGNUP: "SIGNUP",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_ERROR: "SIGNUP_ERROR",
  SIGNUP_FORMDATA: "SIGNUP_FORMDATA",

  WEIGH_ENTRY: "WEIGH_ENTRY",
  WEIGH_ENTRY_SUCCESS: "WEIGH_ENTRY_SUCCESS",
  WEIGH_ENTRY_ERROR: "WEIGH_ENTRY_ERROR",
  WEIGH_ENTRY_FORMDATA: "WEIGH_ENTRY_FORMDATA",
  WEIGH_ENTRY_RESET: "WEIGH_ENTRY_RESET",

  ADD_LORRY: "ADD_LORRY",
  ADD_LORRY_SUCCESS: "ADD_LORRY_SUCCESS",
  ADD_LORRY_ERROR: "ADD_LORRY_ERROR",
  ADD_LORRY_FORMDATA: "ADD_LORRY_FORMDATA",
  ADD_LORRY_RESET: "ADD_LORRY_RESET",

  GET_LORRY: "GET_LORRY",
  GET_LORRY_SUCCESS: "GET_LORRY_SUCCESS",
  GET_LORRY_ERROR: "GET_LORRY_ERROR",
  GET_LOCAL_LORRY: "GET_LOCAL_LORRY",

  SET_BATCH_DATA: "SET_BATCH_DATA",
  SET_BATCH_DATA_SUCCESS: "SET_BATCH_DATA_SUCCESS",
  SET_BATCH_DATA_ERROR: "SET_BATCH_DATA_ERROR",

  SET_LORRY_INFO: "SET_LORRY_INFO",

  ADD_DRIVER_OR_ASSISTANT: "ADD_DRIVER_OR_ASSISTANT",
  ADD_DRIVER_OR_ASSISTANT_SUCCESS: "ADD_DRIVER_OR_ASSISTANT_SUCCESS",
  ADD_DRIVER_OR_ASSISTANT_ERROR: "ADD_DRIVER_OR_ASSISTANT_ERROR",
  ADD_DRIVER_OR_ASSISTANT_FORM_DATA: "ADD_DRIVER_OR_ASSISTANT_FORM_DATA",
  ADD_SUPPLIER: "ADD_SUPPLIER",
  ADD_SUPPLIER_SUCCESS: "ADD_SUPPLIER_SUCCESS",
  ADD_SUPPLIER_ERROR: "ADD_SUPPLIER_ERROR",
  ADD_SUPPLIER_FORM_DATA: "ADD_SUPPLIER_FORM_DATA",
  DRIVER: "driver",
  ASSISTANT: "assistant"
};

export default constants;
