const constants = {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  WEIGH_ENTRY: "WEIGH_ENTRY",
  WEIGH_ENTRY_SUCCESS: "WEIGH_ENTRY_SUCCESS",
  WEIGH_ENTRY_ERROR: "WEIGH_ENTRY_ERROR",
  WEIGH_ENTRY_FORMDATA: "WEIGH_ENTRY_FORMDATA",

  ADD_LORRY: "ADD_LORRY",
  ADD_LORRY_SUCCESS: "ADD_LORRY_SUCCESS",
  ADD_LORRY_ERROR: "ADD_LORRY_ERROR",
  ADD_LORRY_FORMDATA: "ADD_LORRY_FORMDATA",

  GET_LORRY: "GET_LORRY",
  GET_LORRY_SUCCESS: "GET_LORRY_SUCCESS",
  GET_LORRY_ERROR: "GET_LORRY_ERROR"
};

export default constants;
